# ===================================
#  Relation Behavior Config
# ===================================

slides:
    label: jumplink.slideshow::lang.controller.config.relation.label
    view:
        list: $/jumplink/slideshow/models/slide/columns.yml
        toolbarButtons: create|delete
    manage:
        form: $/jumplink/slideshow/models/slide/fields.yml
        recordsPerPage: 20
    emptyMessage: jumplink.slideshow::lang.controller.config.relation.emptyMessage
