# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: jumplink.slideshow::lang.controller.form.slideshows.title

# Model Form Field configuration
form: $/jumplink/slideshow/models/slideshow/fields.yml

# Model Class name
modelClass: JumpLink\Slideshow\Models\Slideshow

# Default redirect location
defaultRedirect: jumplink/slideshow/slideshows

# Create page
create:
    title: jumplink.slideshow::lang.controller.form.slideshows.create
    redirect: jumplink/slideshow/slideshows/update/:id
    redirectClose: jumplink/slideshow/slideshows
    flashSave: jumplink.slideshow::lang.controller.form.slideshows.flashCreate

# Update page
update:
    title: jumplink.slideshow::lang.controller.form.slideshows.update
    redirect: jumplink/slideshow/slideshows
    redirectClose: jumplink/slideshow/slideshows
    flashSave: jumplink.slideshow::lang.controller.form.slideshows.flashUpdate
    flashDelete: jumplink.slideshow::lang.controller.form.slideshows.flashDelete
